create extension if not exists "pgcrypto";
create type public.member_role as enum ('admin','member');
create type public.event_type as enum ('tennis','cycling','aperitif','other');
create type public.attendance_status as enum ('going','maybe','not_going');
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null, nickname text not null unique, role member_role not null default 'member', avatar_url text, tennis_rating integer not null default 1200, cycling_km numeric not null default 0, created_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), title text not null, type event_type not null, starts_at timestamptz not null, location text, description text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.attendances (event_id uuid references public.events(id) on delete cascade, member_id uuid references public.profiles(id) on delete cascade, status attendance_status not null default 'maybe', primary key(event_id,member_id));
create table public.tennis_matches (id uuid primary key default gen_random_uuid(), played_at timestamptz not null default now(), format text not null check(format in ('simple','double')), team_a uuid[] not null, team_b uuid[] not null, score text not null, winner text check(winner in ('A','B')), created_by uuid references public.profiles(id));
create table public.cycling_rides (id uuid primary key default gen_random_uuid(), title text not null, ridden_at date not null, distance_km numeric not null check(distance_km>0), participants uuid[] not null, created_by uuid references public.profiles(id));
create table public.court_cases (id uuid primary key default gen_random_uuid(), title text not null, accusation text not null, accused uuid references public.profiles(id), status text not null default 'open', sanction text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.votes (case_id uuid references public.court_cases(id) on delete cascade, voter_id uuid references public.profiles(id) on delete cascade, guilty boolean not null, primary key(case_id,voter_id));
alter table public.profiles enable row level security; alter table public.events enable row level security; alter table public.attendances enable row level security; alter table public.tennis_matches enable row level security; alter table public.cycling_rides enable row level security; alter table public.court_cases enable row level security; alter table public.votes enable row level security;
create policy "members read profiles" on public.profiles for select to authenticated using (true);
create policy "member updates self" on public.profiles for update to authenticated using (auth.uid()=id);
create policy "members read events" on public.events for select to authenticated using (true);
create policy "members create events" on public.events for insert to authenticated with check (auth.uid()=created_by);
create policy "members manage attendance" on public.attendances for all to authenticated using (auth.uid()=member_id) with check (auth.uid()=member_id);
create policy "members read matches" on public.tennis_matches for select to authenticated using (true);
create policy "members create matches" on public.tennis_matches for insert to authenticated with check (auth.uid()=created_by);
create policy "members read rides" on public.cycling_rides for select to authenticated using (true);
create policy "members create rides" on public.cycling_rides for insert to authenticated with check (auth.uid()=created_by);
create policy "members read cases" on public.court_cases for select to authenticated using (true);
create policy "members create cases" on public.court_cases for insert to authenticated with check (auth.uid()=created_by);
create policy "members vote" on public.votes for all to authenticated using (auth.uid()=voter_id) with check (auth.uid()=voter_id);
